### PR TITLE
SW-4859: enable having multiple components of same-type under same process

### LINKED ISSUE #104: thread-caused malfunction
Hi @Samahu , there're some critical issues in ros2 version (at least ros2 version) srcs.
Case: Since it is components, I'd like to run it under container. I have two lidars and I have to run two os_cloud_node and two os_sensor_node. To obtain resulting point cloud I have to run merger_component (custom component). Now here we got a problem: to provide effective intra-process comm I have to run all five nodes under one container, so it would be one process with several threads. At this point I face at least two problems. First one is: the sensor reinits continuously. The second one is: pointcloud messages could get corrupted.
https://github.com/ouster-lidar/ouster-ros/blob/592e316c6e46ad7e1a353eb93ddf135735a119bf/ouster-ros/src/os_sensor_node.cpp#L697
https://github.com/ouster-lidar/ouster-ros/blob/592e316c6e46ad7e1a353eb93ddf135735a119bf/ouster-ros/src/os_cloud_node.cpp#L177

The problem lays in the static vars. I can't even imaging what for u've used the static var in these cases, but it is big mistake.

### PR DESCRIPTION
**Pull request by Samahu**
## Related Issues & PRs
- Closes #104

## Summary of Changes
- Remove the use of static vars within sensor and cloud components

## Validation
- Test running two components of the same plugin type within the same container

### CODE REVIEW

**Review by bexcite — APPROVED** [review]

**Review by kairenw — APPROVED** [review]

**Comment by Aposhian** [comment]
I'm testing this, and am just getting into a loop where the init id of one of two lidars keeps changing and it just keeps reactivating it.

**Comment by Aposhian** [comment]
Nevermind: it was because I was setting the same ports for both lidars

**Comment by Samahu** [comment]
I did verify it to work with two sensors one container before marking the PR as ready, also have verified using two cloud nodes on a single sensor with a single container.

**Comment by Aposhian** [comment]
Yes I have also verified this to work.

**Pull request merged**
